//
//  VersionFilter.swift
//  PokeDex_Developer
//
//  Created by 유영웅 on 3/21/24.
//

import Foundation

enum VersionFilter: String,CaseIterable {
    case red = "red"
    case blue = "blue"
    case yellow = "yellow"
    case gold = "gold"
    case silver = "silver"
    case crystal = "crystal"
    case ruby = "ruby"
    case sapphire = "sapphire"
    case emerald = "emerald"
    case firered = "firered"
    case leafgreen = "leafgreen"
    case diamond = "diamond"
    case pearl = "pearl"
    case platinum = "platinum"
    case heartgold = "heartgold"
    case soulsilver = "soulsilver"
    case black = "black"
    case white = "white"
    case colosseum = "colosseum"
    case xd = "xd"
    case black2 = "black-2"
    case white2 = "white-2"
    case x = "x"
    case y = "y"
    case omegaRuby = "omega-ruby"
    case alphaSapphire = "alpha-sapphire"
    case sun = "sun"
    case moon = "moon"
    case ultraSun = "ultra-sun"
    case ultraMoon = "ultra-moon"
    case letsGoPikachu = "lets-go-pikachu"
    case letsGoEevee = "lets-go-eevee"
    case sword = "sword"
    case shield = "shield"
    case theIsleOfArmor = "the-isle-of-armor"
    case theCrownTundra = "the-crown-tundra"
    case brilliantDiamond = "brilliant-diamond"
    case shiningPearl = "shining-pearl"
    case legendsArceus = "legends-arceus"
    case scarlet = "scarlet"
    case violet = "violet"
    case theTealMask = "the-teal-mask"
    case theIndigoDisk = "the-indigo-disk"
    
    var name: String {
        switch self {
        case .red: return "레드"
        case .blue: return "블루"
        case .yellow: return "옐로우"
        case .gold: return "금"
        case .silver: return "은"
        case .crystal: return "크리스탈"
        case .ruby: return "루비"
        case .sapphire: return "사파이어"
        case .emerald: return "에메랄드"
        case .firered: return "파이어레드"
        case .leafgreen: return "리프그린"
        case .diamond: return "다이아"
        case .pearl: return "펄"
        case .platinum: return "플래티넘"
        case .heartgold: return "하트골드"
        case .soulsilver: return "소울실버"
        case .black: return "블랙"
        case .white: return "화이트"
        case .colosseum: return "콜로세움"
        case .xd: return "XD"
        case .black2: return "블랙2"
        case .white2: return "화이트2"
        case .x: return "X"
        case .y: return "Y"
        case .omegaRuby: return "오메가루비"
        case .alphaSapphire: return "알파사파이어"
        case .sun: return "썬"
        case .moon: return "문"
        case .ultraSun: return "울트라 썬"
        case .ultraMoon: return "울트라 문"
        case .letsGoPikachu: return "레츠고 피카츄"
        case .letsGoEevee: return "레츠고 이브이"
        case .sword: return "소드"
        case .shield: return "실드"
        case .theIsleOfArmor: return "아일 오브 아머"
        case .theCrownTundra: return "더 크라운 텐드라"
        case .brilliantDiamond: return "브릴리언트 다이아몬드"
        case .shiningPearl: return "샤이닝 펄"
        case .legendsArceus: return "레전드 아르세우스"
        case .scarlet: return "스칼렛"
        case .violet: return "바이올렛"
        case .theTealMask: return "벽록의 가면"
        case .theIndigoDisk: return "남청의 원반"
        }
    }
}
